version: '3.9'

services:
  api:
    image: market-place
    build:
      dockerfile: dev.Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - .docker-compose.env
    ports:
      - '3000:3000'
    volumes:
      - $PWD:/market-place
      - node_modules:/market-place/node_modules
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    env_file:
      - .docker-compose.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  node_modules: